### ISSUE TITLE
Highlight doubles in the Series Checklist

### ISSUE THREAD

**Issue by WicCaesar** [7nik/nm-trade-enhancements#3]
Is it possible for the Enhancer to check the own_count when in the series page, or only in the trades window? It could come in handy in trades if there was a way to highlight doubles in the Series Checklist.

Some ways to depict that:
![doubles](https://github.com/7nik/nm-trade-enhancements/assets/20417329/d09eb099-724b-41d2-a655-9ce901ea7720)
(bold, underlined, or amount)

**Comment by 7nik** [comment]
Now implemented in version 3.3.0. It's optional and off by default. You can enable it on the account page.
